/* ==========================================================================
   Legal content.

   IMPORTANT: These documents are drafted as structurally complete placeholders
   and are NOT legal advice. Every block marked `review: true` needs a lawyer's
   confirmation before launch, and registration details are left as explicit
   TODOs rather than invented.
   ========================================================================== */

export interface LegalSection {
  heading: string;
  paragraphs: string[];
  list?: string[];
  /** Marks a section that must be confirmed by a qualified adviser. */
  review?: boolean;
}

export interface LegalDocument {
  slug: "privacy" | "cookies" | "terms";
  title: string;
  description: string;
  updated: string;
  intro: string;
  sections: LegalSection[];
}

const COMPANY_DETAILS_TODO =
  "TODO(legal): insert the registered company name, company registration number (ЕИК), VAT number where applicable, and registered address. These have deliberately not been invented.";

export const PRIVACY: LegalDocument = {
  slug: "privacy",
  title: "Privacy Policy",
  description:
    "How Bulgaria Digital Services collects, uses and protects personal data under the GDPR.",
  updated: "August 2026",
  intro:
    "This policy explains what personal data Bulgaria Digital Services collects through this website, why it is collected, and what rights you have over it under Regulation (EU) 2016/679 (GDPR).",
  sections: [
    {
      heading: "Data controller",
      review: true,
      paragraphs: [
        "The controller responsible for the personal data described in this policy is Bulgaria Digital Services.",
        COMPANY_DETAILS_TODO,
      ],
    },
    {
      heading: "What we collect",
      paragraphs: [
        "We collect only what a specific purpose requires. There is no profiling, no data brokerage and no sale of personal data under any circumstances.",
      ],
      list: [
        "Enquiry data you submit through the contact form: name, company, email, optional phone number, and the project information you choose to provide.",
        "Any project summary you choose to attach from the Solution Architect or the project consultant.",
        "Analytics data, only where you have consented to it — see the cookie policy.",
        "Standard server logs generated by the hosting provider, including IP address, for security and abuse prevention.",
      ],
    },
    {
      heading: "Data that never leaves your browser",
      paragraphs: [
        "The Solution Architect and the project consultant run entirely in your browser. Your answers are held in local storage and session storage on your own device and are not transmitted to any server unless you explicitly choose to send them with an enquiry.",
        "Clearing your browser storage removes that data permanently, and we have no copy of it.",
      ],
    },
    {
      heading: "Legal basis",
      review: true,
      paragraphs: [
        "Enquiry data is processed on the basis of steps taken at your request prior to entering a contract (Article 6(1)(b) GDPR), and our legitimate interest in responding to business enquiries (Article 6(1)(f)).",
        "Analytics data is processed solely on the basis of your consent (Article 6(1)(a)), which you may withdraw at any time.",
      ],
    },
    {
      heading: "How long we keep it",
      review: true,
      paragraphs: [
        "Enquiry correspondence is retained for as long as needed to handle the enquiry and any resulting engagement, and thereafter for the period required by applicable accounting and limitation rules.",
        "TODO(legal): confirm concrete retention periods against Bulgarian accounting and commercial law before publication.",
      ],
    },
    {
      heading: "Who we share it with",
      paragraphs: [
        "Personal data is shared only with processors necessary to operate this site and respond to enquiries — hosting, email delivery and, where consented, analytics.",
        "We do not sell personal data, and we do not share it for advertising purposes.",
      ],
    },
    {
      heading: "Your rights",
      paragraphs: [
        "Under the GDPR you have the right to access your data, to have inaccurate data corrected, to request erasure, to restrict or object to processing, and to data portability. Where processing is based on consent, you may withdraw that consent at any time without affecting processing already carried out.",
        "To exercise any of these rights, contact us using the details on the contact page. You also have the right to lodge a complaint with the Bulgarian Commission for Personal Data Protection.",
      ],
    },
    {
      heading: "Security",
      paragraphs: [
        "This site is served over HTTPS with standard security headers. Enquiry data is validated on the server and transmitted only to the configured recipient. Access to enquiry correspondence is limited to the people handling it.",
      ],
    },
  ],
};

export const COOKIES: LegalDocument = {
  slug: "cookies",
  title: "Cookie Policy",
  description:
    "What this site stores in your browser, which categories are optional, and how your consent choice changes behaviour technically.",
  updated: "August 2026",
  intro:
    "This site uses a small number of storage mechanisms. Some are required for it to work; the rest are optional and disabled until you allow them. Your choice changes what is technically collected, not merely what is displayed.",
  sections: [
    {
      heading: "Necessary",
      paragraphs: [
        "Required for the site to function and cannot be switched off. This category includes your cookie consent choice itself, which is stored locally so you are not asked on every visit.",
      ],
      list: [
        "bds_consent_v1 — your consent preferences, stored in local storage.",
        "Security and routing state maintained by the hosting platform.",
      ],
    },
    {
      heading: "Analytics",
      paragraphs: [
        "Optional. When enabled, Google Analytics 4 measures how the site is used so it can be improved. This site implements Google Consent Mode v2: if you decline analytics, the denied state is sent to the measurement layer and collection genuinely does not take place.",
        "If no measurement ID is configured for a given deployment, no analytics script is loaded at all, regardless of consent.",
      ],
    },
    {
      heading: "Marketing",
      paragraphs: [
        "Optional and currently unused. No advertising or remarketing tags run on this site. The category is declared so that your preference is already recorded and honoured if that ever changes.",
      ],
    },
    {
      heading: "Interactive tool storage",
      paragraphs: [
        "The Solution Architect stores your answers in local storage so you can return without losing your configuration. The project consultant and the contact handoff use session storage, which is cleared when you close the tab.",
        "Neither is used for tracking, and neither is transmitted anywhere unless you send it with an enquiry.",
      ],
    },
    {
      heading: "Changing your choice",
      paragraphs: [
        "You can change your preferences at any time by clearing this site's data in your browser settings, which restores the consent banner on your next visit.",
      ],
    },
  ],
};

export const TERMS: LegalDocument = {
  slug: "terms",
  title: "Terms of Service",
  description:
    "Terms governing use of this website and the basis on which Bulgaria Digital Services provides its services.",
  updated: "August 2026",
  intro:
    "These terms govern your use of this website. Engagements for actual project work are governed by a separate written agreement signed by both parties, not by this page.",
  sections: [
    {
      heading: "Who operates this site",
      review: true,
      paragraphs: [
        "This website is operated by Bulgaria Digital Services.",
        COMPANY_DETAILS_TODO,
      ],
    },
    {
      heading: "Nature of the information",
      paragraphs: [
        "The content of this site is provided for information. Descriptions of solutions, capabilities and process are indicative and do not constitute a binding offer.",
        "No pricing is published on this site. Scope and price are established through discovery and recorded in a written agreement before any work begins.",
      ],
    },
    {
      heading: "The interactive tools",
      paragraphs: [
        "The Solution Architect and the project consultant produce indicative technical guidance generated from your inputs. Their output is a starting point for a conversation, not a specification, an estimate, or professional advice on which decisions should be made without further discussion.",
        "Complexity classifications are relative indicators only and do not represent a price, a timescale, or a commitment.",
      ],
    },
    {
      heading: "Intellectual property",
      paragraphs: [
        "The design, text and code of this website are the property of Bulgaria Digital Services. Client names, brands and project materials shown in case studies remain the property of their respective owners and are used with permission for illustration.",
      ],
    },
    {
      heading: "Client ownership of delivered work",
      review: true,
      paragraphs: [
        "For delivered projects, ownership of source code, data and infrastructure is transferred to the client as set out in the applicable written agreement. This site does not vary those terms.",
        "TODO(legal): confirm that this statement matches the standard client contract wording before publication.",
      ],
    },
    {
      heading: "Limitation of liability",
      review: true,
      paragraphs: [
        "This website is provided on an as-is basis. To the extent permitted by applicable law, Bulgaria Digital Services accepts no liability for interruptions, technical errors, or indirect losses arising from use of this website.",
        "TODO(legal): confirm this clause is enforceable and appropriately scoped under Bulgarian law.",
      ],
    },
    {
      heading: "Governing law",
      review: true,
      paragraphs: [
        "TODO(legal): confirm governing law and jurisdiction wording before publication.",
      ],
    },
  ],
};

export const LEGAL_DOCUMENTS = [PRIVACY, COOKIES, TERMS];
